### ISSUE TITLE
Credit Card Details being stored in Database

### ISSUE THREAD

**Issue by Gerhardt0011** [strider-tech/peach-payments#16]
Not sure if this is intended but it seems that the credit card details as a whole including the full card number, expiry date, and CVV is being stored in the database in clear text, not sure why this has to be done as it seems that the code makes use of Peach Payments tokenization, or is it only in test mode that this occurs ?

**Comment by DmitryDash** [comment]
Hi @Gerhardt0011,
Thank you for your comments.

Yes, you're right, this flow `server-to-server` should be implemented with secure features.
I will add this as improvement.

For now you can just extend the `PaymentCard` model and implement your security options.
